version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - run:
          name: install packer
          command: sudo apt-get install packer -y          
      - run:
          name: aws cli
          command: sudo pip install awscli
      - run:
          name: Validate Packer Template
          command: ./packer validate ubuntu-ami.json
      - run:
          name: Build AMI
          command: |
            ./packer build \
            ubuntu-ami.json
workflows:
  version: 2
  build-ami:
    jobs:
    - build